# enables a network-wide join message for when a player joins the network
global-network-join: true

# enables a network-wide leave message for when a player leaves the network
global-network-leave: true

# enables a network-wide message that notifies players when a player switches between servers when true global-network-switch: true
global-network-switch: true

# enables a network-wide messaging system that allows players to communicate between servers on the proxy
global-messages: true


# for all message options, you can insert a hex code (example: {#ff0066}). Characters after this hex code will turn the color of the code. Multiple hex codes can be used to make a string multicolored.
# you can also insert tags like {bold} and {italic} to style your messages. Please refer to the documentation for this plugin for more information.

# the default color to be used for a player's name in messages when they have not set one
default-player-color: "#fcfcfc"

# options from this list will be randomly chosen to be displayed when a player joins the network
# {player} will be replaced by the player name
join-message-options:
  - "{player} joined the network"

# options from this list will be randomly chosen to be displayed when a player leaves the network
# {player} will be replaced by the player name leave-message-options:
leave-message-options:
  - "{player} left the network"

# options from this list will be randomly chosen to be displayed when a player changes between two servers on the network 
# {player} will be replaced by the player name
# {prev} will be replaced by the server the player is connecting from
# {cur} will be replaced by the server the player is connecting to
switch-message-options:
  - "{player} left {prev} and joined {cur}"


# the prefix to global messages on other servers
# {cur} will be replaced by the current server
# {player} will be replaced by the player's name
global-message-prefix: "[{cur}] - {player}: "

# whether player's messages will be global by default
global-message-default: true

# options for a network-wide resource pack
network-resource-pack:
  # whether or not to use a resource pack
  enabled: false
  # the url of the resource pack
  url: "pack.zip"
  # the hash of the zip file
  # - the hash currently does nothing, as I don't know how to properly parse this into a byte array
  #   if you know, please open a PR or issue ticket on my github. Thanks.
  sha1-hash: "hash" 
  # the prompt that users will recieve when connecting
  prompt: "{#ff2200}This proxy reccomends the use of a datapack for a better player experience."
  # whether or not the resource pack is required to play on the network
  required: false
  # a list of servers that will not have a resource pack applied to it
  # I recomend this for modded servers because resource packs can cause issues there
  except:
    - "modded"

# options for discord integration
discord:
  # enables discord features
  enabled: false 

  # your bot token
  bot-token: "^token"

  # the main channel where general proxy activity will be reported
  proxy-channel-id: "^channel-id"

  # Color of the discord embed for join messages
  join-color: "#00ff00"
  # Color of the discord embed for leave messages
  leave-color: "#ff0000"
  # Color of the discord embed for switch messages
  switch-color: "#ffff00"

  # all text options support markdown formatting
  # these messages DO NOT support the hex codes like above
  text-configuration:
    online-message: "## Proxy Online"
    offline-message: "## Proxy Offline"

    # on proxy startup, lists available servers
    server-count: true

    # on startup and shutdown, show an image if you provided one
    display-icon: false

    # whether or not to sync player chat with discord
    player-chat-sync:

      # enable the feature
      enabled: false

      # a prefix to player messages in discord - these can be formatted like above
      # this only applies when global messaging is disabled
      player-message-prefix: "[{cur}] - <{player}>: "

      # replaces the set color for a player's name with a user's role color
      # when sending messages from discord to minecraft
      discord-role-color: true

      # the servers (as listed in your velocity.toml) and their corresponding channel id
      # each server will report its activity to it's specified channel
      server-channel-ids: 
        ^lobby: "lobby-channel-id"
        ^vanilla: "vanilla-channel-id"

