# enables a network-wide join message for when a player joins the network
global-network-join: true

# enables a network-wide leave message for when a player leaves the network
global-network-leave: true

# enables a network-wide message that notifies players when a player switches between servers when true
global-network-switch: true


# for all message options, you can insert a hex code (example: {#ff0066}). Characters after this hex code will turn the color of the code. Multiple hex codes can be used to make a string multicolored.

# options from this list will be randomly chosen to be displayed when a player joins the network
# {player} will be replaced by the player name
join-message-options:
  - "{player} joined the network"

# options from this list will be randomly chosen to be displayed when a player leaves the network
# {player} will be replaced by the player name
leave-message-options:
  - "{player} left the network"

# options from this list will be randomly chosen to be displayed when a player changes between two servers on the network 
# {player} will be replaced by the player name
# {prev} will be replaced by the server the player is connecting from
# {cur} will be replaced by the server the player is connecting to
switch-message-options:
  - "{player} left {prev} and joined {cur}"

discord:
  # enables discord SRV mode
  enabled: false 
  bot-token: "{token}"
  channel-id: "{channel-id}"

  # Color of the discord embed for join messages
  join-color: "#00ff00"
  # Color of the discord embed for leave messages
  leave-color: "#ff0000"
  # Color of the discord embed for switch messages
  switch-color: "#ffff00"

  # all text options support markdown formatting
  # these messages DO NOT support the hex codes like above
  text-configuration:
    online-message: "## Proxy Online"
    offline-message: "## Proxy Offline"

    # on proxy startup, lists available servers
    server-count: true

    # on startup and shutdown, show an image if you provided one
    display-icon: false