name: ProxyMessages
version: 4.0.1
main: dev.ogblackdiamond.proxymessages.ProxyMessages
description: Paper plugin to interface with Velocity
author: BlackDiamond
api-version: '1.20'

dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false
